{% set version = "0.2" %}


package:
  name: otfmi
  version: {{ version }}

source:
  fn: otfmi-{{ version }}.tar.gz
  url: https://github.com/openturns/otfmi/archive/v{{ version }}.tar.gz
  sha256: 141338ccf24543798f5567665c77b52d877b96ed153ba4021d21c56ef67c32aa

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - python
    - openturns
    - pyfmi

test:
  imports:
    - otfmi

about:
  home: http://openturns.org/
  license: LGPL3
  license_file: COPYING.LESSER
  summary: FMI models manipulation module

extra:
  recipe-maintainers:
    - jschueller
