{% set version = "0.12" %}

package:
  name: otfmi
  version: {{ version }}

source:
  fn: otfmi-{{ version }}.tar.gz
  url: https://github.com/openturns/otfmi/archive/v{{ version }}.tar.gz
  sha256: f8c4da2070e094d3741fef7d540f84893b6b834ada012bc04c00b1f2669c5fcd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.6
    - openturns
    - pyfmi
    - assimulo >=3.0
    - dill

test:
  imports:
    - otfmi

about:
  home: http://openturns.org/
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: FMI models manipulation module

extra:
  recipe-maintainers:
    - jschueller
