travis:
  secure:
    BINSTAR_TOKEN: SItAjkO5CAKxGR6d7wTBtQ8As0P1uaI2N37EopR7AbMB8fO0rzmnqWfKNiHgO5Xo/cOTtmMwTjYiWbcaw2PxOUHFPuvUpT1+bDZKePX8oGy9B7gupmD1FzgsVreHFDRy0BvHLGxpeZ2mxtQV3zPKy+sI/Tj9sO1Zq4Vi0dp03pJ7DQxzmteg300vTz60Fo3iLP3i+BsBsIsbT53MlAKE9pAZEgdRRJChU5ert6ozDQGwlfZjrmhylvBFLBuB9N7g/wRcA64M2nhVeZRQQuUk7ktck9RomfhzAlHbh9qA+HahrSCynX9agIUltUhkHnM7RIRe9kmnl55KfRN1t7dWkRUIhxPjAtigNLlxVIlyDwov9R4syUgkKQgCj96XA+x3/K5Cq7QkcEFAEVZGA/pVwB9/laBPDsil1nUXyDYK5d+8EH6KiyhYcqZjoEjMLgfTypDDwDIAZcyIcB7XPV0wO+iuI+lgwOnTrWNS+z/XlMmTtB1I9VXIx6ve/sR/f1XPdh2kJhJsMOvbfYkMgUIZcFAvF8UJhSoARANXkCuz76nx7m99jxhxZSc2loNY0GO7pBU0PIcKfUD94aBmKWVwTAhFsblpr0luh4T0wPV3c17kkJxn0YWS3XEqBzyYzOcmog4ocyIoF86fM9gvQoHPai07YDoBxQldmiD/jKZZW0U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
