travis:
  secure:
    BINSTAR_TOKEN: e0Xq6xdJ7W44Lsqy2asHoTz5JMj5zZRi3j5szDg0wbU4WBH2Qm0DYnDnfLMBaDVJc/xc2ld7YlqJoEBxTVqkjKRT59EFd+j7IhTzAAPyYjJrqoDKUuda/J7YNYfGdoG0Tma8shqDnRvzMFoLua4qoah4onjikyvhEdlJJ9O+lrzArD4kofsggotTpvLpeHlQbw7lSps9moSKdJyYQiIONfgAnPF+YtfXtEyLvkyv9qdFESlAgsE1Hq5fvORcj1Agy82mjIrtODaklAubkS1TnUVLWiFlAxAIqKYSbBg9JhCI8yCKWIGpUsT8IVGw6ysRZNwmmPW0HAU8c5DqrLAFN1pk4jZ2RpLHy4mLDD7Y7dSs5JKClkB8+fKWeLkhWBMI1cN1vdE87yfAl8HjGz7bKNe7fG4Qhat6EZrQU6FFyZsU2t5byGCDbWVvVoHUBph6L3zacc9PcDQWtzGxdEI3aKo45p0YFUI9C57o8w98vmdDtSs0g4Ma9JNk0Mbj4J382qKywCQ72K7UwGpPOCv3phnCMSk6BQrSkSly5DJiw3htNiELKnzsw7GmaCudRr8WLNiuwcOWwehJtYyBZ5umkUOnvs33MIF9+dcR6ow2hXvgW9cXnBX0aotlNVD1RaUrt4qepm5iCtk82+ErSOjAu+T09t0jgeONvOzSq02LL18=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
