travis:
  secure:
    BINSTAR_TOKEN: MXbdqahCbOti7HIS39ZipJjgUPsyPJ8u0RSKbMFwo7kelLOoqp0nglQxv6MVB4aaFUYZzhw0NU1n8OoCa+eftoKez5oHQxD3kGjkzaK5cQkd6lAQypDsDo3h1Rg4KsWPyjKzYN5ottg1KMZs5hx0s7GKKm26BldjvPe84jKOuGweN5oGSY7D2o6MiKL+TK4/WH2Rg9gvF+9VbkaAQwiO7oTt8ljGBYF9Rl/hORZ7sTm23mEMIfEcWbS1DobynWZk1t1rgEZevd9oGrluBjZ98JHbadKYsA0STBTiG6KDk/DRwIcrgb3xC/8ecDFVmYI8MmdpqjAZ3PtI+NNR5G5qOrXxARVqAiCiRGDxkMc61hHG2FisLT4ioWnurt6VNjbMYZR28dpEyOYEjQfnmWPwvc7KS0RFq2ekbPlGsOai4SADpY/WY59+aNN9LQF87NTIW1n3vjsVySQDa/TalUUatCQV6pULFLw6MjVj5UcZZGjs1jB6wSdWf2X40RoQ/HbA0irW8EG2Fj8p+o+vl+/hN/WkkjtmnK3bR5sWwelBgR1YywhgqcerxYPwG9pFBYg7zz4EdCwiLPTmxDCGadSJZmHPYTn4h/eTgvYDfJgWbHA4OjO6Tn5/bkaMu2hIu8qstaKpwUwRCFQ1BNS6PW+RzNpRRMKT3TDRBdQmqwCT27E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
