travis:
  secure:
    BINSTAR_TOKEN: RD13ASSNAI15Si+wZhNtmCLEI+zW7FDIBOPBtLmDwAIPAJ+SH4Ta499i1dtPIGlDqlZ/tKfMQGkTYOYrPsONRTR0gvbTrHL03C6y4fstkMvHG1KO0teENiN+owSdK9x3Y6Yard5D4jXqGtO8sUm1P15F0l/4FCMnHTTsshAxOcOxHorGQ5ktl8GYdNVUAV97qYrWsa5r8aRzVrxCZXJYwUV0IisbM4O7sMYd396+bq8Qpec+Zz6b89mFqgt0A/kyi72yZCyjLYs9x3wEbudcrnFhk37X2mL3XyL/fXjkYXKTixvxCE6gt7oh38zHXy5edENJcD7Ck6NGMDA5ZrAIbmX4gc9KQzS2fJMsZwa1xx8guEgJCTh14rjB9A0KhYE570/ZBbN5Y0Px078GqcUzSuhQ+J4T25wluRIdXxpQpV46YzsNLOxy9xQCqJMpPTlR6esK8GrHCA6Tb3sRfgLw54ga1phbXqJ9HTvckvJUFUk+a9ErOJ+8oAo9ci9oa5FHaZaWBNmNBEHBXpDbjLOpx3D6Ksk1MHk3eTUuMQUa570taUYxYybd5rWlG0WExgjXAEtk7T+UuiFlEK3nGKQGd3JwphmdSM0ZCYG3e6vXSBRGn02VD61j3UDBhGgwc3jicG2rRaL5pt3G0abi1ADSzbbs4vqVTZ4itZUvgznZpTw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
